### ISSUE TITLE
Couldn't find the requested file 'marshall islands.png'

### ISSUE THREAD

**Issue by James103** [sadmoody/covid-predictor#10]
It looks like there is currently no flag available for Marshall Islands, which has probably just been added to the tracker. When the website attempts to show the flag, it instead returns a 404 error with the following text:
`Couldn't find the requested file /static/images/flags/marshall islands.png in sadmoody/covid-predictor.`

**Comment by sadmoody** [comment]
Thanks James! That's all fixed now!

That's very appreciated 👍
