### ISSUE TITLE
Couldn't find the requested file 'palau.png'

### ISSUE THREAD

**Issue by James103** [sadmoody/covid-predictor#17]
It looks like there is currently no flag available for Palau, which has probably just been added to the tracker. When the website attempts to show the flag, it instead returns a 404 error with the following text:
> Couldn't find the requested file /static/images/flags/palau.png in sadmoody/covid-predictor.

**Comment by James103** [comment]
@sadmoody First draft for your inspiration: 
Palau: ![image](https://user-images.githubusercontent.com/37945304/127384658-7138f349-b92f-4dd8-9335-66e6f7c91b8a.png)
Summer Olympics 2020: ![image](https://user-images.githubusercontent.com/37945304/127384781-9a2d7c5f-526e-48fa-b045-c61885c968e8.png)
Summer Olympics 2020 ("Tokyo" instead of "2020"): ![image](https://user-images.githubusercontent.com/37945304/127384842-7eac8e5d-787b-4958-9f7d-66f660f64c7b.png)
Kiribati: ![image](https://user-images.githubusercontent.com/37945304/127384880-c3289344-64fd-42fd-ba57-0a54ed6aa030.png)
Micronesia: ![image](https://user-images.githubusercontent.com/37945304/127384902-1c5517ad-a515-4aff-91fe-36776d73caf3.png)
Samoa: ![image](https://user-images.githubusercontent.com/37945304/127384927-312eaa9c-cdfc-4979-ac23-bc9a179b5e98.png)

Feel free to use and/or modify any of these images as you wish.

**Comment by sadmoody** [comment]
James, these are great! 🥇 

Gonna be a bit picky here and see if you can change the squares on the olympic flag to be more round (might not be possible).

Feel free to set up a pull request and I'll approve it - based on your previous issues filed I imagine you'll know how to name them correctly!

If you can't get the rounded rings, then all good, just put them through as is. I like the 2020 more than the Tokyo flag - will be more scalable for future olympics but hopefully we'll never need a 2024!

**Comment by James103** [comment]
As requested, 2020 Tokyo Olympics flag (2nd draft with circles): ![image](https://user-images.githubusercontent.com/37945304/127599097-daceea4e-3dd2-4f74-9ca6-244b6d2439b1.png)

**Comment by sadmoody** [comment]
Perfect! 

Wanna do a PR? Let me know if you can't be bothered and I'll just set it up. I know there's people that take it super seriously on here.
