### ISSUE TITLE
Infection and Death Rates per capita

### ISSUE THREAD

**Issue by CodeByMistakes** [sadmoody/covid-predictor#7]
The Health Secretary for the UK has responded to the report that the UK will soon have the worst Covid--19 / Coronavirus figures in Europe by saying that the numbers should be taken on a per-capita basis.

I would like to see a checkbox next to the drop-down that allow the rankings on a per-capita basis.

**Comment by sadmoody** [comment]
Hey @CodeByMistakes sorry it took me so long to get back to you here!

I'm not sure how to effectively visualise per capita. It would also be quite slow when represented as error bars as we get slow-downs of at least 1000x for even the smallest countries.

I understand the motivation of wanting to see per-capita, as that would allow you to compare countries' response to each other proportionatly, but I think that's out of scope for what I was trying to do!

Code is there, though, and by all means you're welcome to have a go 👍
