### ISSUE TITLE
Couldn't find the requested file 'solomon islands.png'

### ISSUE THREAD

**Issue by James103** [sadmoody/covid-predictor#9]
It looks like there is currently no flag available for the Solomon Islands, which has probably just been added to the tracker. When the website attempts to show the flag, it instead returns a 404 error with the following text:
`Couldn't find the requested file /static/images/flags/solomon islands.png in sadmoody/covid-predictor.`

**Comment by sadmoody** [comment]
Thanks for the report! Fixed in less than 15 minutes!

🔥🔥🔥
